# Generated by Django 4.2.7 on 2025-08-25 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('architecture', 'Architecture'), ('civil_engineering', 'Civil Engineering'), ('mep', 'MEP Engineering'), ('structural', 'Structural Engineering'), ('project_management', 'Project Management'), ('quantity_surveying', 'Quantity Surveying'), ('other', 'Other')], max_length=100, null=True)),
                ('experience_level', models.CharField(choices=[('student', 'Student'), ('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='student', max_length=50)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'accounts_profile',
            },
        ),
    ]
